version: "2.1"

services:    
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: file_batch
      
    healthcheck:
      test: mysqladmin ping -h localhost -p$$MYSQL_ROOT_PASSWORD && test '0' -eq $$(ps aux | awk '{print $$11}' | grep -c -e '^mysql$$')
      interval: 1s
      retries: 120
    ports:
      - 3308:3306
      
  file-batch-app:
    image: file-batch
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
            db:
                condition: service_healthy
    ports:
    - 8085:8085
 
